### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by octfx** [StarCitizenWiki/mediawiki-extensions-PictureHtmlSupport#1]
* [x] Add a hook to let other extensions register additional `<source>` in `<picture>`
* [x] Works with MMV
* [x] Works with `wgParserEnableLegacyMediaDOM = false;`
* Less hacky way to override the HTML?

HTML ref:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source

Related task:
* Use of HTML5 element (e.g. `<picture>`, `<source>`: https://phabricator.wikimedia.org/T25932
* Allow to render WebP thumbnails in addition to PNG/JPG in MediaWiki core: https://phabricator.wikimedia.org/T282453
* Extend srcset with more widths and the size attribute: https://phabricator.wikimedia.org/T76966
